name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - dvelop
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.14', '1.15']
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go
